//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Online csevegõszoftver
//  @ File Name : @Csevego
//  @ Date : @2020_12_01
//  @ Author : @Fodor Balázs
//
//




public class Admin {
	public void create_room() {
	}
	
	public void delete_room() {
	}
	
	public void invite_user() {
	}
	
	public void kick_user() {
	}
	
	public void ban_user() {
	}
}
