//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Online csevegõszoftver
//  @ File Name : @Csevego
//  @ Date : @2020_12_01
//  @ Author : @Fodor Balázs
//
//




public class Chat {
	public String[] Message;
	public void validUsers() {
	}
	
	public void GetMessage() {
	}
	
	public void SendMessage() {
	}
	
	public void Private_message() {
	}
}
