//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Online csevegõszoftver
//  @ File Name : @Csevego
//  @ Date : @2020_12_01
//  @ Author : @Fodor Balázs
//
//




public class Register {
	public void registation() {
	}
}
