//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : @Online csevegõszoftver
//  @ File Name : @Csevego
//  @ Date : @2020_12_01
//  @ Author : @Fodor Balázs
//
//




public class Users {
	public void join_room() {
	}
	
	public void leave_room() {
	}
	
	public interface Test {
	}
}
